// Providers — barrel export (registry + adapter base + quirks + catalog types).
export {
  listProviderTemplates,
  getProviderTemplate,
  isProviderTemplate,
  getAdapter,
  adapterForProvider,
  familyDefaultTransforms,
  defaultTransformsForCatalog,
} from "./registry";
export {
  ProviderAdapter,
  OpenAICompatibleAdapter,
  AnthropicCompatibleAdapter,
  wireFmtOf,
  wireKindOf,
  endsWithKnownSuffix,
  standardPath,
  endpointPathFor,
  resolveKind,
  composeUrl,
  applyAuthHeaders,
  type WireFmt,
  type EndpointRoute,
  type ResolveUrl,
  type ResolvePath,
  fetchModelList,
  modelIds,
  modelsFormatOf,
  normalizeModels,
  normalizeOpenAIModels,
  normalizeAnthropicModels,
  DEFAULT_ANTHROPIC_VERSION,
  type BuildCtx,
  type BuiltRequest,
  type UsageCtx,
  type KeyUsageResult,
  type ModelsCtx,
  type ModelsResult,
  type ModelsFormat,
  type FetchModelListOptions,
  type ModelListTransport,
  type ModelListResponse,
  type TestModelCtx,
  type TestModelResult,
  type TestProviderCtx,
  type TestProviderResult,
  type AdapterRequest,
  type AdapterHttpResponse,
  minimalProbeBody,
} from "./base";
export type { UpstreamModel } from "../formats/wire/models";
export { applyTemplateDefaults, capabilitiesForTemplate } from "./quirks";
export type {
  ProviderTemplate,
  ProviderDefaults,
  ProviderQuirks,
  TemplateField,
} from "./types";
